name: Windows dev actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Cloning code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Restore package
        run: |
          dotnet restore ./WPFUI/WPFUI.csproj /p:PublishReadyToRun=true

      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4

      - name: build with Devenv
        run: |
          cd "D:\a\windows-pipeline\windows-pipeline\WPFUI"
          DevEnv WPFUI.sln /Build Release

      - name: Disable Out of Process Building
        run: .\DisableOutOfProcBuild.exe
        working-directory: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild

      - name: Build with devenv.com
        run: |
          cd "D:\a\windows-pipeline\windows-pipeline\WPFUISetup"
          DevEnv WPFUISetup.vdproj /Build Release
          dir "D:\a\windows-pipeline\windows-pipeline\WPFUISetup\Release"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows build
          path: D:\a\windows-app\windows-app\MovableApp\SNAPxr\Release\SNAPxr.msi
